In [1]:
import numpy as np

In [9]:
n_V = 6
Adj_Mat1 = np.zeros((n_V,n_V))
for i in range(n_V):
    Adj_Mat1[i][5] = Adj_Mat1[5][i] = 1
Adj_Mat1[5][5] = 0
Adj_Mat1

array([[0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 0.]])

In [17]:
n_V = 8
Adj_Mat2 = np.zeros((n_V,n_V))
for i in range(n_V):
    for j in range(i+1,n_V):
        print("Enter edge for ",i,j,":")
        e=int(input())
        Adj_Mat2[i][j]=Adj_Mat2[j][i]=e
Adj_Mat2

Enter edge for  0 1 :
1
Enter edge for  0 2 :
1
Enter edge for  0 3 :
0
Enter edge for  0 4 :
0
Enter edge for  0 5 :
0
Enter edge for  0 6 :
1
Enter edge for  0 7 :
1
Enter edge for  1 2 :
1
Enter edge for  1 3 :
1
Enter edge for  1 4 :
1
Enter edge for  1 5 :
1
Enter edge for  1 6 :
1
Enter edge for  1 7 :
1
Enter edge for  2 3 :
1
Enter edge for  2 4 :
0
Enter edge for  2 5 :
1
Enter edge for  2 6 :
1
Enter edge for  2 7 :
1
Enter edge for  3 4 :
1
Enter edge for  3 5 :
1
Enter edge for  3 6 :
0
Enter edge for  3 7 :
0
Enter edge for  4 5 :
0
Enter edge for  4 6 :
1
Enter edge for  4 7 :
0
Enter edge for  5 6 :
0
Enter edge for  5 7 :
0
Enter edge for  6 7 :
1


array([[0., 1., 1., 0., 0., 0., 1., 1.],
       [1., 0., 1., 1., 1., 1., 1., 1.],
       [1., 1., 0., 1., 0., 1., 1., 1.],
       [0., 1., 1., 0., 1., 1., 0., 0.],
       [0., 1., 0., 1., 0., 0., 1., 0.],
       [0., 1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 0., 1., 0., 0., 1.],
       [1., 1., 1., 0., 0., 0., 1., 0.]])

In [142]:
n_V = 5
Adj_Mat3 = np.zeros((n_V,n_V))
for i in range(n_V):
    for j in range(i+1,n_V):
        print("Enter edge for ",i,j,":")
        e=int(input())
        Adj_Mat3[i][j]=Adj_Mat3[j][i]=e
Adj_Mat3

Enter edge for  0 1 :
1
Enter edge for  0 2 :
0
Enter edge for  0 3 :
0
Enter edge for  0 4 :
1
Enter edge for  1 2 :
1
Enter edge for  1 3 :
0
Enter edge for  1 4 :
0
Enter edge for  2 3 :
1
Enter edge for  2 4 :
1
Enter edge for  3 4 :
1


array([[0., 1., 0., 0., 1.],
       [1., 0., 1., 0., 0.],
       [0., 1., 0., 1., 1.],
       [0., 0., 1., 0., 1.],
       [1., 0., 1., 1., 0.]])

In [59]:
def get_independent_sets(G):
    temp_G = G.copy()
    S=set()
    for init in range(len(temp_G)):
        I = [init]
        temp_G[0,:] = temp_G[:,0] = 0
        while(temp_G.sum()>0):
            v = get_non_adjacent(G,I)
            if v==-1:
                break
            temp_G[v,:] = 0
            temp_G[:,v] = 0
            I.append(v)
        S.add(tuple(set(I)))
    return S

In [35]:
def get_non_adjacent(G,I): #Finds non_adjacent edges in graph G wrt vertex set I
    n = len(G)
    for v in range(n):
        flag = True
        for i in I:
            if G[v][i] == 1 or i==v:
                flag = False
                break
        if flag==True:
            return v
        #print(v,i)
        #input()
    return -1

In [62]:
get_independent_sets(Adj_Mat2)

{(0, 3), (0, 4, 5), (1,), (2, 4), (3, 6), (3, 7)}

In [91]:
def get_odd_cycles(G):
    graph = matrix_to_dict(G)
    cycles = [[node]+path  for node in graph for path in dfs(graph, node, node)]
    return cycles

def dfs(graph, start, end):
    fringe = [(start, [])]
    while fringe:
        state, path = fringe.pop()
        if path and state == end:
            yield path
            continue
        for next_state in graph[state]:
            if next_state in path:
                continue
            fringe.append((next_state, path+[next_state]))

def matrix_to_dict(Matrix):
    d1 = {}
    for v in range(len(Matrix)):
        d1[v] = [i for i in range(len(Matrix)) if Matrix[v][i]==1]
    return d1

In [94]:
odd_cycles=[i for i in get_odd_cycles(Adj_Mat2) if len(i)%2==0]

In [144]:
def is_induced_with_more_than_one_cord(cycle,G):
    count=0
    temp_G = G.copy()
    for i in range(len(G)):
        for j in range(len(G)):
            if i>j:
                temp_G[i][j]=0
    s = set()
    for v in cycle:
        for w in cycle:
            if temp_G[v][w]==1:
                s.add(tuple(set([v,w])))
    if len(s)>len(cycle):
        return True
    else:
        return False

def get_induced_odd_cycles_atleast5(G):
    l1 = []
    odd_cycles=[i for i in get_odd_cycles(G) if len(i)%2==0 and len(i)>4]
    for cycle in odd_cycles:
        if is_induced_with_more_than_one_cord(cycle,G):
            l1.append(cycle)
    return l1

def is_very_strongly_perfect(G):
    cycles = get_induced_odd_cycles_atleast5(G)
    if len(cycles)>0:
        return True
    else:
        return False

In [141]:
is_very_strongly_perfect(Adj_Mat2)

True

In [145]:
is_very_strongly_perfect(Adj_Mat3)

False